Remove redundant include of Rts.h in EventLogWriter.h
`EventLogWriter.h` doesn't use anything from `Rts.h`, the include is
redundant. This include is ignored when we include

```
Rts.h -> RtsAPI.h -> rts/EventLogWriter.h -> Rts.h
```

but can can cause problem when we include `RtsApi.h` directly with
errors like

```
In file included from /usr/lib/ghc-8.6.2/include/RtsAPI.h:20:
In file included from
/usr/lib/ghc-8.6.2/include/rts/EventLogWriter.h:14:
In file included from /usr/lib/ghc-8.6.2/include/Rts.h:185:
/usr/lib/ghc-8.6.2/include/rts/storage/GC.h:187:29: error: unknown type
name 'Capability'
StgPtr  allocate          ( Capability *cap, W_ n );
```

Test Plan: ./validate

Reviewers: simonmar, bgamari, afarmer, erikd, alexbiehl

Reviewed By: bgamari, alexbiehl

Subscribers: rwbarton, carter

Differential Revision: https://phabricator.haskell.org/D5395