Testsuite: only show output diff when test is expected to pass
Don't let the output of tests that either have missing libraries or are
expected to be broken obscure real failures.

This makes it easier to analyse the testlogs.

The only consequence is that when a test fails because a certain library
isn't installed, you have to check the all.T file in which the test is
defined to actually find out _which_ library that is. Before it would
print something like

    Compile failed (status 256) errors were:

    stm052.hs:10:8: error:
     Could not find module ‘System.Random’
     Use -v to see a list of the files searched for.

And now it doesn't. I think this is an acceptable tradeoff.

Differential Revision: https://phabricator.haskell.org/D945