Revert "UNREG: use __builtin___clear_cache where available"
This reverts commit 6dd1257fdd4d18e84d32e89bf0ec664b3c8f7b93.

Change fails vaildation:
  rts/sm/Storage.c:1351:20: error:
     error: ‘gcc_clear_cache’ defined but not used [-Werror=unused-function]
     STATIC_INLINE void gcc_clear_cache(void * begin, void * end)