rts: fix filename case for mingw32 target
The failure is visible when we build a cross-compiler
from linux to mingw32 as:

```
    $ ./configure --host=x86_64-pc-linux-gnu \
                  --target=x86_64-w64-mingw32
    $ make
    rts/linker/PEi386.c:159:10: error:
         fatal error: Psapi.h: No such file or directory
         #include <Psapi.h>
                  ^~~~~~~~~
        |
    159 | #include <Psapi.h>
        |          ^
```

The problem here is case-sensitive linux filesystem. On windows
it does not matter what case is used for includes and libraries.

mingw32 provides all libraries and headers lowercase. This change
fixes case for <dbghelp.h>, <psapi.h>, -ldbghelp, -lpsapi.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

Reviewers: bgamari, erikd, simonmar

Reviewed By: bgamari

Subscribers: rwbarton, thomie, carter

Differential Revision: https://phabricator.haskell.org/D4247