libdw: enable support only on i386 and amd64
Summary:
Currently libdw requires per-arch implementation of
set_initial_registers() function.

Otherwise build fails with linkage error
(seen on sparc):

  rts/dist/build/libHSrts_thr-ghc7.11.20151129.so:
      undefined reference to `set_initial_registers'
  collect2: error: ld returned 1 exit status
  `gcc' failed in phase `Linker'. (Exit code: 1)
  make[1]: *** [ghc/stage2/build/tmp/ghc-stage2] Error 1

Converted link-time error to compile-time error,
added arch whitelist.

Signed-off-by: Sergei Trofimovich <siarheit@google.com>

Reviewers: austin, thomie, bgamari

Reviewed By: bgamari

Differential Revision: https://phabricator.haskell.org/D1567